### PR TITLE
Tests plus fixes

### PR DESCRIPTION
**Pull request by vibhavp**
This change is [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/35)

### CODE REVIEW

**Comment by sbinet** [comment]
it seems a file is missing:

```
=== RUN   TestSpec
--- FAIL: TestSpec (0.00s)
	exec_test.go:277: open testdata/spec/modules.json: no such file or directory
FAIL
```

**Comment by vibhavp** [comment]
Yep, I added it in the latest commit.

**Comment by sbinet** [comment]
thanks.

**Comment by sbinet** [comment]
Reviewed 56 of 64 files at r1.
Review status: 56 of 64 files reviewed at latest revision, 12 unresolved discussions.

---

*[disasm/disasm.go, line 33 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvQyif1W42nO2-OKiBZ:-KvQyif1W42nO2-OKiB_:b4yxd7e) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L33)):*
> ```Go
> 	NewStack    *StackInfo // non-nil if the instruction creates or unwinds a stack.
> 	Block       *BlockInfo // non-nil if the instruction starts or ends a new block.
> 	Unreachable bool       // whether the operator can be reached while execution
> ```

`s/while/during/`

also: maybe it would be easier to read in the code later on if the condition was reversed. _ie_, `Reachable bool` instead of `Unreachable bool` ?
because, later on, in the code we do a lot of `if !instr.Unreachable { ... }`. double negatives are hard(er) to grasp and grok.

---

*[disasm/disasm.go, line 34 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvQyv_SjD2YGQCJFxFH:-KvQyv_SjD2YGQCJFxFI:b24u7gr) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L34)):*
> ```Go
> 	Block       *BlockInfo // non-nil if the instruction starts or ends a new block.
> 	Unreachable bool       // whether the operator can be reached while execution
> 	// IsReturn is true when executing this instruction will result in the
> ```

`s/when/if/` ?

---

*[disasm/disasm.go, line 48 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvQzFGBGDrUkCgcEFfP:-KvQzFGBGDrUkCgcEFfQ:b82ate) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L48)):*
> ```Go
> 	StackTopDiff int64 // The difference between the stack depths at the end of the block
> 	PreserveTop  bool  // Whether the value on the top of the stack should be preserved while unwinding
> 	IsReturn     bool  // Whether the unwind is equivalent to a return
> ```

`s/the unwind is equivalent/unwinding the stack is equivalent/` ?

---

*[disasm/disasm.go, line 198 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR0jDjXFv3_krcfEc-:-KvR0jDjXFv3_krcfEc0:btn2416) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L198)):*
> ```Go
> 				elemsDiscard := int(curDepth) - int(prevDepth)
> 				if elemsDiscard < -1 {
> 					println(curDepth, prevDepth, prevDepthIndex)
> ```

remove or use `logger.Printf`

---

*[disasm/disasm.go, line 231 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR15Y5IjxidR5zwqBX:-KvR15Y5IjxidR5zwqBY:b-ujvlaa) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L231)):*
> ```Go
> 			stackDepths.Push(stackDepths.Top())
> 			if !instr.Unreachable {
> 				// If this new block is unreachable, its
> ```

you say unreachable but you test whether it is reachable.
which one is it? :)

---

*[disasm/disasm.go, line 256 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR1KNiqtlLIii6tpm8:-KvR1KNiqtlLIii6tpm9:bpv55kj) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L256)):*
> ```Go
> 			} else {
> 				curDepth := stackDepths.Top()
> 				// whenever we take a branch, the stack is unwinded
> ```

`s/unwinded/unwound/`

---

*[exec/exec_test.go, line 44 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5cevS3dxB0SjBkfa:-KvR5cevS3dxB0SjBkfb:bah66js) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L44)):*
> ```Go
> var reValue = regexp.MustCompile(`(.+)\:(.+)`)
> 
> func parseFloat(str string, base int) float64 {
> ```

could you add a few dedicated tests for `parseFloat` ?

---

*[exec/exec_test.go, line 45 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR2Nts3kAhxpBcKGlY:-KvR2Nts3kAhxpBcKGlZ:bsz4zbd) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L45)):*
> ```Go
> 
> func parseFloat(str string, base int) float64 {
> 	hexFloat, _ := regexp.MatchString("0x", str)
> ```

please do not silently drop errors on the floor.
`panic(err)` if they are not `nil`.

also, perhaps put the `hexFloat` computation closer to where it's needed/used.

---

*[exec/exec_test.go, line 46 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR2b3hCdG5X45Fy9rt:-KvR2b3hCdG5X45Fy9ru:bfrev5) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L46)):*
> ```Go
> func parseFloat(str string, base int) float64 {
> 	hexFloat, _ := regexp.MatchString("0x", str)
> 	isNanOrInf, _ := regexp.MatchString("(nan|inf)", str)
> ```

_ditto_

also: what about casing? `NaN`, `NAN`, `Inf`?

---

*[exec/exec_test.go, line 128 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR57-HWmbLYoFBmjAw:-KvR57-HWmbLYoFBmjAx:b-ugb0t8) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L128)):*
> ```Go
> 	matches := reValue.FindStringSubmatch(str)
> 	if matches == nil {
> 		panic("Invalid value expression")
> ```

perhaps print it as part of the panic message?

---

*[exec/exec_test.go, line 161 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5Gw6OctrqFKsDUVe:-KvR5Gw6OctrqFKsDUVf:b-qxoig2) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L161)):*
> ```Go
> 			n = math.Float64bits(v.(float64))
> 		default:
> 			panic("invalid value type")
> ```

perhaps print it too

---

*[exec/memory.go, line 209 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR62b_sKYLsKZ2fXA7:-KvR62b_sKYLsKZ2fXA8:bdu4sun) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/memory.go#L209)):*
> ```Go
> 
> func (vm *VM) growMemory() {
> 	_ = vm.fetchInt8() // reserved
> ```

a bit of explanation wouldn't hurt here :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35)*

**Comment by vibhavp** [comment]
Review status: 56 of 64 files reviewed at latest revision, 12 unresolved discussions.

---

*[disasm/disasm.go, line 33 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvQyif1W42nO2-OKiBZ:-KvXQs1DiFesO7VowBlU:byhemac) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L33)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/while/during/`

also: maybe it would be easier to read in the code later on if the condition was reversed. _ie_, `Reachable bool` instead of `Unreachable bool` ?
because, later on, in the code we do a lot of `if !instr.Unreachable { ... }`. double negatives are hard(er) to grasp and grok.
</blockquote></details>

In an average WebAssembly function, most operators are reachable (as unreachable operators are never executed). Therefore, unreachability is a special case, where we will either skip type checking (`validate.go`), not update stack top/max stack depth (`disasm.go`), or skip compiling the operator entirely (`compile.go`). 

---

*[disasm/disasm.go, line 34 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvQyv_SjD2YGQCJFxFH:-KvXK8t3_Qi2BcSTQGu5:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L34)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/when/if/` ?
</blockquote></details>

Done.

---

*[disasm/disasm.go, line 48 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvQzFGBGDrUkCgcEFfP:-KvST3_-CENoPFX9Aufp:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L48)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/the unwind is equivalent/unwinding the stack is equivalent/` ?
</blockquote></details>

Done.

---

*[disasm/disasm.go, line 198 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR0jDjXFv3_krcfEc-:-KvST471NS4PmdCOhenu:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L198)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

remove or use `logger.Printf`
</blockquote></details>

Done.

---

*[disasm/disasm.go, line 231 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR15Y5IjxidR5zwqBX:-KvSbvmOmK7-KiSsZBjI:b-j5wnam) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L231)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

you say unreachable but you test whether it is reachable.
which one is it? :)
</blockquote></details>

clarified the comment.

---

*[disasm/disasm.go, line 256 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR1KNiqtlLIii6tpm8:-KvSbzFN0mgel5XWi_Bt:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/disasm/disasm.go#L256)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/unwinded/unwound/`
</blockquote></details>

Done.

---

*[exec/exec_test.go, line 44 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5cevS3dxB0SjBkfa:-KvSbzxfrhKSU-EeaYdm:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L44)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

could you add a few dedicated tests for `parseFloat` ?
</blockquote></details>

Done.

---

*[exec/exec_test.go, line 45 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR2Nts3kAhxpBcKGlY:-KvSc-JCR7LYmIF_0y1S:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L45)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please do not silently drop errors on the floor.
`panic(err)` if they are not `nil`.

also, perhaps put the `hexFloat` computation closer to where it's needed/used.
</blockquote></details>

Done.

---

*[exec/exec_test.go, line 46 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR2b3hCdG5X45Fy9rt:-KvSc-sPKrBcgZx9rFvi:befxt3c) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L46)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

_ditto_

also: what about casing? `NaN`, `NAN`, `Inf`?
</blockquote></details>

not needed, the spec tests only use `nan` and `inf`

---

*[exec/exec_test.go, line 128 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR57-HWmbLYoFBmjAw:-KvSc5vB8AYodblS4O5H:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L128)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

perhaps print it as part of the panic message?
</blockquote></details>

Done.

---

*[exec/exec_test.go, line 161 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5Gw6OctrqFKsDUVe:-KvXK4P496wiA6yab6q0:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L161)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

perhaps print it too
</blockquote></details>

Done.

---

*[exec/memory.go, line 209 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR62b_sKYLsKZ2fXA7:-KvXK54d8JJcVaeN4U4x:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/memory.go#L209)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

a bit of explanation wouldn't hurt here :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35)*

**Comment by sbinet** [comment]
Reviewed 5 of 64 files at r1, 2 of 3 files at r2.
Review status: 63 of 64 files reviewed at latest revision, 1 unresolved discussion.

---

*[exec/exec_test.go, line 161 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5Gw6OctrqFKsDUVe:-KvzyZKf50bonEPH_3Tf:bwnrow7) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L161)):*
<details><summary><i>Previously, vibhavp (Vibhav Pant) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please also print the value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35)*

**Comment by vibhavp** [comment]
Review status: 63 of 64 files reviewed at latest revision, 1 unresolved discussion.

---

*[exec/exec_test.go, line 161 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5Gw6OctrqFKsDUVe:-Kw0CJOHDnDSVMvRC1j-:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L161)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please also print the value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35)*

**Comment by sbinet** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[exec/exec_test.go, line 161 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-KvR5Gw6OctrqFKsDUVe:-Kw0FljW9oKhvqiKawlZ:b-vz19im) ([raw file](https://github.com/go-interpreter/wagon/blob/8d5df7e00677426f2ec6cd02aa24d02b5849431b/exec/exec_test.go#L161)):*
<details><summary><i>Previously, vibhavp (Vibhav Pant) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(FYI, you could also have done it like so: `panic(fmt.Sprintf("invalid value type: %T(%v)", v, v))`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35)*

**Comment by sbinet** [comment]
:lgtm:

please fix the commit messages of `97b6492`, `49a33a2`, `9a2f1a2` and `75529a7` and I'll merge.

thanks a lot (and apologies for having let this down on the floor)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-:-Kw0G7yIzJaUsXv8JDGk:b8nrn0g)*

**Comment by vibhavp** [comment]
Squashed and fixed, thanks.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/35#-:-Kw0pz5btXCvM87tcJNH:b-xs5pfh)*

**Pull request merged**
