### PR TITLE
exec: add example for VM usage

### PR DESCRIPTION
**Pull request by sbinet**
Updates go-interpreter/wagon#60.

---
This change is [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/61)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm: 

Thank you very much for writing this. Should definitely help me get started!
I only have a few requests for more words.

I'd suggest linking to this example from the repo's README.
For this being sufficient for newcomers on its own, it'd be great if it also included the passing of a `string` or `[]byte` to wasm.

And since we're talking, do you have any experience with producing wasm from C++ or any other language? Should I expect `wagon` to work with modules produced by `emscripten`, for example? I'm particularly curious how `emscripten` handles references to the C/C++ standard library. I read that it uses musl and that if you don't ask it to optimize for space it will produce humongous modules. 

---

Review status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @sbinet)

---

*[exec/vm_example_test.go, line 24 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtLTRZ31F3uXR249B7:-LEtLTRZ31F3uXR249B8:b-d3smhf) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L24)):*
> ```Go
> 	}
> 
> 	m, err := wasm.ReadModule(bytes.NewReader(raw), func(name string) (*wasm.Module, error) {
> ```

it'd be good, at least for me, to explain a bit how linking works in the wasm world, and how that affects wagon. In this test we're manually handling the loading of one module (`add-ex-main.wast`) and then providing it with a resolver that handles both the imported "add" and "go". Would it also be possible for `add-ex.wast` and `add-ex-main.wast` to be linked together by a tool from the toolchain?
Consider adding some words about this if there's anything to be said.

---

*[exec/vm_example_test.go, line 37 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtN0ox2E2EwQGWgzMY:-LEtN0ox2E2EwQGWgzMZ:b-6zx6i0) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L37)):*
> ```Go
> 			}
> 			return add, nil
> 		case "go":
> ```

call out the awesome fact that "go" is not a module we're loading, but one we're synthesizing.

---

*[exec/vm_example_test.go, line 46 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtIr-O-FdKkn6t3AxA:-LEtIr-O-FdKkn6t3AxB:b-ym8bdj) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L46)):*
> ```Go
> 				Entries: []wasm.FunctionSig{
> 					{
> 						Form:       0,
> ```

pls comment this `Form` field

---

*[exec/vm_example_test.go, line 55 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtL6ka2sI7aEddyHOx:-LEtL6ka2sI7aEddyHOy:b-haza1o) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L55)):*
> ```Go
> 					Sig:  &m.Types.Entries[0],
> 					Host: reflect.ValueOf(print),
> 					Body: &wasm.FunctionBody{},
> ```

what's up with this ptr to an empty struct? If it is needed, consider adding a comment (there are none at the `Function` definition site); one would expect it to be either-or with `Host`.

---

*[exec/vm_example_test.go, line 75 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtNJldChy4xmOVrnGO:-LEtNJldChy4xmOVrnGP:b92s0m6) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L75)):*
> ```Go
> 	vm, err := exec.NewVM(m)
> 	if err != nil {
> 		log.Fatalf("could not create wagon vm: %v", err)
> ```

nit: here and elsewhere, since `err` is known no be `!= nil`, using `%s` would be clearer.

---

*[exec/vm_example_test.go, line 106 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtHs03DinKZzjQE2os:-LEtHs03DinKZzjQE2ot:b-8kdcx5) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L106)):*
> ```Go
> }
> 
> func compileWast2Wasm(fname string) ([]byte, error) {
> ```

I'm not sure I understand the need for this function, and calling it "compile" sure is misleading :)
I'd say make the test read the wasm files directly and put the assembler instructions in the main test func. You can also link to the issue calling out for an assembler to be implemented.

---

*[exec/testdata/add-ex.wast, line 2 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtNpD967PsvzBlbTLg:-LEtNpD967PsvzBlbTLh:b-7tixrq) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/testdata/add-ex.wast#L2)):*
> ```WebAssembly
> (module
>   (type (;0;) (func (param i32 i32) (result i32)))
> ```

unless the `;0;`bit is understood by everybody, it would perhaps be worth an explanation

---

*[exec/testdata/add-ex.wast, line 3 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtOAiD0-dwDOzPrLbz:-LEtOAiD0-dwDOzPrLc-:b-ipfe1s) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/testdata/add-ex.wast#L3)):*
> ```WebAssembly
> (module
>   (type (;0;) (func (param i32 i32) (result i32)))
>   (func (;0;) (type 0) (param i32 i32) (result i32)
> ```

for my edification - what does `type 0` mean here? I realize it's referring to the type we defined above, but it seems redundant with the rest of the function signature...

---


*Comments from [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/61#-:-LEtOUOS6Y3tFH5dwNb7:b-hpmh2i)*

**Comment by andreimatei** [comment]
To answer my last question, I've had good luck compiling simple C functions with `emcc -Os`.

---

Review status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @sbinet)

---



*Comments from [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/61#-:-LF0cIMz5PkUjl2nJ4jr:b-d72lsl)*

**Comment by andreimatei** [comment]
Review status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @sbinet)

---

*[exec/vm_example_test.go, line 71 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LF3jeto9E95Tp8rUVP3:-LF3jeto9E95Tp8rUVP4:bfgnjjk) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L71)):*
> ```Go
> 		}
> 		return nil, fmt.Errorf("module %q unknown", name)
> 	})
> ```

you forgot to check for the returned err here

---


*Comments from [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/61)*

**Comment by sbinet** [comment]
Review status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @andreimatei and @sbinet)

---

*[exec/vm_example_test.go, line 24 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtLTRZ31F3uXR249B7:-LG4dTFC7uXJZZ6eSJUs:bcyigrh) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L24)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it'd be good, at least for me, to explain a bit how linking works in the wasm world, and how that affects wagon. In this test we're manually handling the loading of one module (`add-ex-main.wast`) and then providing it with a resolver that handles both the imported "add" and "go". Would it also be possible for `add-ex.wast` and `add-ex-main.wast` to be linked together by a tool from the toolchain?
Consider adding some words about this if there's anything to be said.
</blockquote></details>

Done. (I think)

---

*[exec/vm_example_test.go, line 37 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtN0ox2E2EwQGWgzMY:-LG4cQ_i8ifnz51thM_j:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L37)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

call out the awesome fact that "go" is not a module we're loading, but one we're synthesizing.
</blockquote></details>

Done.

---

*[exec/vm_example_test.go, line 46 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtIr-O-FdKkn6t3AxA:-LG4cPtY0jpwUBX3OICg:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L46)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment this `Form` field
</blockquote></details>

Done.

---

*[exec/vm_example_test.go, line 55 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtL6ka2sI7aEddyHOx:-LG4cOcy6EhybYg5XMbg:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L55)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's up with this ptr to an empty struct? If it is needed, consider adding a comment (there are none at the `Function` definition site); one would expect it to be either-or with `Host`.
</blockquote></details>

Done.

---

*[exec/vm_example_test.go, line 71 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LF3jeto9E95Tp8rUVP3:-LG4cLqLD8yftduXEWE4:b-ujps41) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L71)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you forgot to check for the returned err here
</blockquote></details>

Done. (good catch!)

---

*[exec/vm_example_test.go, line 75 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtNJldChy4xmOVrnGO:-LG4c7oMBjjlWzdcG65Y:b69ks80) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L75)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: here and elsewhere, since `err` is known no be `!= nil`, using `%s` would be clearer.
</blockquote></details>

I usually prefer to use `%v` for all kind of `error` values and only use `%s` for real strings.

---

*[exec/vm_example_test.go, line 106 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtHs03DinKZzjQE2os:-LG4bZ5pE2CNZ7cv8pgV:b-vnu2sg) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/vm_example_test.go#L106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure I understand the need for this function, and calling it "compile" sure is misleading :)
I'd say make the test read the wasm files directly and put the assembler instructions in the main test func. You can also link to the issue calling out for an assembler to be implemented.
</blockquote></details>

I am leaning towards just adding a snarky comment about the lack of WAST->WASM compilation support (linking towards the issue) and leave it at that.
it's really to show the expected workflow (but pushing the missing features under the rug so everything looks kind of clean.)
it's also to show what's supposed to be inside the `.wasm` files, and looking at a `.wast` file is easier for humans :)

---

*[exec/testdata/add-ex.wast, line 2 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtNpD967PsvzBlbTLg:-LG4f5Q_EWPP1IsTKXSy:b-rb23q6) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/testdata/add-ex.wast#L2)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

unless the `;0;`bit is understood by everybody, it would perhaps be worth an explanation
</blockquote></details>

Done. (I have linked to the specs. `(; ;)` is just an inline comment like `/* */` is in `C/C++`.)
here, `(; 0 ;)` is just to help the human reader notice the index of that `type`.

---

*[exec/testdata/add-ex.wast, line 3 at r1](https://reviewable.io/reviews/go-interpreter/wagon/61#-LEtOAiD0-dwDOzPrLbz:-LG4fWvI4rtU83yJYN8X:b-hv84s8) ([raw file](https://github.com/go-interpreter/wagon/blob/d0fddf2b2b00cc5208a71387ad0798364a7e2e70/exec/testdata/add-ex.wast#L3)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

for my edification - what does `type 0` mean here? I realize it's referring to the type we defined above, but it seems redundant with the rest of the function signature...
</blockquote></details>

yeah... redundant but this allows to have a linear definition for the module.

---


*Comments from [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/61)*

**Comment by sbinet** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed, 8 unresolved discussions (waiting on @andreimatei)

---



*Comments from [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/61)*

**Pull request merged**
