### PR TITLE
exec/internal/compile: New package (plus field rename in package disasm).

### PR DESCRIPTION
**Pull request by vibhavp**
compile provides functions for compiling WebAssembly bytecode to a
format better suited for execution.

---
This change is [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/25)

### CODE REVIEW

**Comment by sbinet** [comment]
could you add some tests? especially tests that exercize the rewriting of disasm instructions.

---

Review status: 0 of 3 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-:-KrWDkVkrfDL3djtNd-v:b-5u0ejl)*

**Comment by sbinet** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[disasm/disasm.go, line 232 at r2](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWEn34yskR7YvYqo2a:-KrWEn34yskR7YvYqo2b:byui1vp) ([raw file](https://github.com/go-interpreter/wagon/blob/d2f72a155e46d72c3264cf26f691433c5d09d973/disasm/disasm.go#L232)):*
> ```Go
> 			top -= len(fn.Sig.ParamTypes)
> 			top += len(fn.Sig.ReturnTypes)
> 			top = int(stackDepths.SetTop(uint64(top)))
> ```

if I am not mistaken, `SetTop` returns its input value as output value.
so this line is just doing the same than what was originally written, just a bit more confusing.

---

*[disasm/disasm.go, line 244 at r2](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWFJPs4fTkShFg9asH:-KrWFJPs4fTkShFg9asI:b-jwdqn5) ([raw file](https://github.com/go-interpreter/wagon/blob/d2f72a155e46d72c3264cf26f691433c5d09d973/disasm/disasm.go#L244)):*
> ```Go
> 			switch op {
> 			case ops.GetLocal, ops.GetGlobal:
> 				top = stackDepths.SetTop(top + 1)
> ```

I would just write this as:
```go
top++
stackDepths.SetTop(top)
disas.checkMaxDepth(int(top))
```

---

*[internal/stack/stack.go, line 22 at r2](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWF_e6zizf-cPI3QU5:-KrWF_e6zizf-cPI3QU6:b-dg0di4) ([raw file](https://github.com/go-interpreter/wagon/blob/d2f72a155e46d72c3264cf26f691433c5d09d973/internal/stack/stack.go#L22)):*
> ```Go
> }
> 
> func (s *Stack) SetTop(v uint64) uint64 {
> ```

do we really need `SetTop` to return its input value?
it returns it unchanged, so, why bother?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/25)*

**Comment by vibhavp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 14 unresolved discussions.

---

*[disasm/disasm.go, line 232 at r2](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWEn34yskR7YvYqo2a:-KrZcCdIcWOZqiqU-adu:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/d2f72a155e46d72c3264cf26f691433c5d09d973/disasm/disasm.go#L232)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

if I am not mistaken, `SetTop` returns its input value as output value.
so this line is just doing the same than what was originally written, just a bit more confusing.
</blockquote></details>

Done.

---

*[disasm/disasm.go, line 244 at r2](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWFJPs4fTkShFg9asH:-KrZcD7kNz9oiJ7n9PIE:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/d2f72a155e46d72c3264cf26f691433c5d09d973/disasm/disasm.go#L244)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

I would just write this as:
```go
top++
stackDepths.SetTop(top)
disas.checkMaxDepth(int(top))
```
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 48 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW2TczG8KfIwQ0DvFt:-KrZVvX2jwTiXAYvdeEI:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L48)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/access or modify/access nor modify/`
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 49 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW2Z4cShsKXC3yuoEk:-KrZVw7tZawOTgDoeujQ:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L49)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/it's/its/`
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 56 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW2l4wp54XUf4CEkqK:-KrZVx27EZsc94IutNQH:bxlcelk) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L56)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/it's/its/`

also, there's probably a word missing or something, because I don't really understand that sentence: "of its stack on top the root stack".
could you clarify or reword?
</blockquote></details>

Yeah, that doesn't make much sense. Should be fixed now.

---

*[exec/compile/compile.go, line 75 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW3FQZJ19xmcH534MI:-KrZcEmGQBa4IAvdsl8N:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L75)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please document this type and its use. (and/or relate it with the doc blurb above)
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 81 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW3R_XPQ9Ue0eXT2p2:-KrZcF9fsRzNRe-03H-l:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L81)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please document this type.
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 85 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWCa7HpLuI7mnctBHL:-KrZbNdEGSNWx7zwJKr4:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L85)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

this comment makes a reference to a variable name `blocks` from somewhere in the `Compile` function.
it could use some more explaining: what it really represents, what it's used for.
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 88 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW3ZSCVrQcZUuVW750:-KrZbQkI2eMJJRQHeeyM:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L88)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/relevent/relevant/g`
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 105 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW3w01ir4K6Ut95SRI:-KrZcFu5V11nBJYEFCvw:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L105)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/if yes/In that case/`
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 108 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW482yP-GIh8eJHppF:-KrZcGO4ZPf3PD19FScS:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L108)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/need to patched/need to be patched/`
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 115 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW4IBXOWkIa4rUJRIR:-KrZcHE5LK2ukV5BgDL-:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L115)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please document this function.
</blockquote></details>

Done.

---

*[exec/compile/compile.go, line 126 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrW8YAUYmeF4YG-XtHR:-KrZc9F7zC-wYzlFvVHt:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/701c6c3f4b7e5624bb4939842fdd006b41cde9e2/exec/compile/compile.go#L126)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

you should probably reword: `s/the offset and the alignment/the alignment and the offset/` and `s/latter/former/` so getting the second element of `instr.Immediates` is less confusing.
</blockquote></details>

Done.

---

*[internal/stack/stack.go, line 22 at r2](https://reviewable.io:443/reviews/go-interpreter/wagon/25#-KrWF_e6zizf-cPI3QU5:-KrZcI2uv9Rm0LL-bnsj:b-vcoaro) ([raw file](https://github.com/go-interpreter/wagon/blob/d2f72a155e46d72c3264cf26f691433c5d09d973/internal/stack/stack.go#L22)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

do we really need `SetTop` to return its input value?
it returns it unchanged, so, why bother?
</blockquote></details>

Yeah, I've removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/25)*

**Comment by sbinet** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/25)*

**Comment by sbinet** [comment]
LGTM.
please squash all `compile` relevant commits into one, all `stack` ones into one and `disasm` into one.

thanks.

**Comment by vibhavp** [comment]
Done.

**Pull request merged**
