### PR TITLE
Small fixes to wasm + new validate package

### PR DESCRIPTION
**Pull request by vibhavp**
This change is [Reviewable](https://reviewable.io/reviews/go-interpreter/wagon/13)

### CODE REVIEW

**Comment by sbinet** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[wasm/section.go, line 631 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-Kp-Z38PmXT4s26jVLqH:-Kp-Z38Qgj_XyPW-yJYE:b-s5a6lm) ([raw file](https://github.com/go-interpreter/wagon/blob/7e29eff1b944ac1c80033829233433d76339eefa/wasm/section.go#L631)):*
> ```Go
> 	Locals         []LocalEntry
> 	Code           []byte
> 	MaxDepth       int // the maximum stack depth that can be reached while executing this body
> ```

why don't we need those anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by vibhavp** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[wasm/section.go, line 631 at r1](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-Kp-Z38PmXT4s26jVLqH:-Kp49xiPLxUirMyWf5pX:b-6bko1b) ([raw file](https://github.com/go-interpreter/wagon/blob/7e29eff1b944ac1c80033829233433d76339eefa/wasm/section.go#L631)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

why don't we need those anymore?
</blockquote></details>

These fields aren't actually specified in the wasm spec for `function_body`: https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#function-bodies

I had added these fields for execution purposes, so that they can be used to correctly allocate the stack and local var vector/array. To keep the API design consistent, I have moved them to the `disasm` package, as they are better suited to that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by sbinet** [comment]
LGTM.
except the commit messages aren't following our convention :)
they should be of the form:

```
package: short description

More detailed description if needed.
```

also, I would split `1075803` into the part that is really related to `buf` and the part about the correct `Stringer` implementation.

(we shouldn't probably squash that PR into just one big commit and keep the granularity as it is)

---

Reviewed 1 of 6 files at r1, 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-:-KpAep3CpaSgRkrTgxAk:b-4yf3dj)*

**Comment by sbinet** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by vibhavp** [comment]
> also, I would split 1075803 into the part that is really related to buf and the part about the correct Stringer implementation.

Done.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-:-KpBPh40wQwn1zjnkfUW:bh9gr1w)*

**Comment by sbinet** [comment]
Review status: 6 of 11 files reviewed at latest revision, 17 unresolved discussions.

---

*[validate/error.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSfuNPsXIk2vdI41r8:-KqSfuNQ4PPh5fUgpehu:b9m2377) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L1)):*
> ```Go
> package validate
> ```

please add a license header.

---

*[validate/error.go, line 11 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSqO0RKouGHb7bNhmL:-KqSqO0RKouGHb7bNhmM:ba4zis9) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L11)):*
> ```Go
> )
> 
> type ValidateError struct {
> ```

from a user's perspective, this type is called `validate.ValidateError`.
why not just call it `Error`. it would remove some stuttering: `validate.Error`.

---

*[validate/error.go, line 12 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSqoPhCruy8YgJkeUr:-KqSqoPhCruy8YgJkeUs:bkgm1uw) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L12)):*
> Offset   int
please document of what that `Offset` is (bytes, ...) and into what.

---

*[validate/error.go, line 21 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSr7V7RIXAi5-pNVrY:-KqSr7V7RIXAi5-pNVrZ:b-etc7it) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L21)):*
> ```Go
> }
> 
> var ErrStackUnderflow = errors.New("stack underflow")
> ```

`s/stack underflow/validate: stack underflow/`

---

*[validate/error.go, line 52 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSrMpO5ypmAfiPlWNE:-KqSrMpO5ypmAfiPlWNF:b5er811) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L52)):*
> ```Go
> 
> type InvalidTypeError struct {
> 	Expected wasm.ValueType
> ```

to match what is usually done in tests, I would rename `Expected` into `Wanted`.
and put `Got` before `Wanted`.

---

*[validate/error.go, line 57 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSiKEzSYU3DuYJZF-B:-KqSiKEzSYU3DuYJZF-C:b4x37np) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L57)):*
> ```Go
> 
> func (e InvalidTypeError) Error() string {
> 	return fmt.Sprintf("invalid type: wanted %s, got %s", e.Expected.String(), e.Got.String())
> ```

no need to explicitly call `.String()`, let `fmt.Sprintf` use the `Stringer` interface. do this instead:
```go
return fmt.Sprintf("invalid type. got %s, want %s", e.Got, e.Expected)
```

---

*[validate/operand.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSnYQ0QEpqvjlGYPkJ:-KqSnYQ0QEpqvjlGYPkK:b9m2377) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/operand.go#L1)):*
> ```Go
> package validate
> ```

please add a license header.

---

*[validate/validate.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSnarY63lRraZCrXe_:-KqSnarY63lRraZCrXea:b9m2377) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L1)):*
> ```Go
> package validate
> ```

please add a license header.

---

*[validate/validate.go, line 44 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSo6P1TYeSUftr5LRz:-KqSo6P1TYeSUftr5LS-:b-dlp1ne) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L44)):*
> ```Go
> 
> 	for {
> 		curPc := vm.pc()
> ```

it's not clear to me why we do this.
is it a debugging leftover ?

---

*[validate/validate.go, line 47 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSs8VG_7sU1cPM3lW5:-KqSs8VG_7sU1cPM3lW6:b-y7as14) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L47)):*
> ```Go
> 		_ = curPc
> 		op, err := vm.codeReader.ReadByte()
> 		if err == io.EOF {
> ```

you should also probably return that error (and possibly "decorate" it) if that error is not `nil` (and not `io.EOF`.)

---

*[validate/validate.go, line 301 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSq8o0oJAtfAno3k1i:-KqSq8o0oJAtfAno3k1j:b-235bzt) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L301)):*
> ```Go
> 			}
> 
> 			// remaining checks are done dynamically
> ```

could you note in the comment what are these remaining checks?

---

*[validate/validate.go, line 323 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSq0UQJ7hQHZ8X0VJw:-KqSq0UQJ7hQHZ8X0VJx:b-vlc732) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L323)):*
> ```Go
> 			}
> 
> 			// last 2 poppoed values should be of the same type
> ```

typo: `poppoed`

---

*[validate/validate.go, line 338 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSomKCVbW87AjdPp9l:-KqSomKCVbW87AjdPp9m:br7lw32) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L338)):*
> ```Go
> }
> 
> func VerifyModule(module *wasm.Module) error {
> ```

please document this exported method.

---

*[validate/vm.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSpj-XfoUIWKod3S3N:-KqSpj-XfoUIWKod3S3O:b9m2377) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L1)):*
> ```Go
> package validate
> ```

please add a license header.

---

*[validate/vm.go, line 19 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSp7jicLb-jMZu_vfr:-KqSp7jicLb-jMZu_vfs:b-qv9o2t) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L19)):*
> ```Go
> 	origLength int // the original length of the bytecode stream
> 
> 	codeReader *bytes.Reader
> ```

I would just call it `code`.

---

*[validate/vm.go, line 47 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqStlUyWbAODMXogdZ1:-KqStlUyWbAODMXogdZ2:b-bs8qc3) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L47)):*
> ```Go
> 
> func (vm *mockVM) fetchUint32() (i uint32, err error) {
> 	err = binary.Read(vm.codeReader, binary.LittleEndian, &i)
> ```

that's fine for the moment (we don't really know the perf bottlenecks) but please put a TODO to use the direct, reflection-less `binary.LittleEndian.Uint32` method.

---

*[validate/vm.go, line 52 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSu7qpwDlk5EKF6Hn5:-KqSu7qpwDlk5EKF6Hn6:bymeqem) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L52)):*
> ```Go
> 
> func (vm *mockVM) fetchUint64() (i uint64, err error) {
> 	err = binary.Read(vm.codeReader, binary.LittleEndian, &i)
> ```

that's fine for the moment (we don't really know the perf bottlenecks) but please put a TODO to use the direct, reflection-less `binary.LittleEndian.Uint64` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by vibhavp** [comment]
Review status: 6 of 11 files reviewed at latest revision, 17 unresolved discussions.

---

*[validate/error.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSfuNPsXIk2vdI41r8:-KqU1zcRVM2ep1H3cUM7:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L1)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please add a license header.
</blockquote></details>

Done.

---

*[validate/error.go, line 11 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSqO0RKouGHb7bNhmL:-KqU2-tAOHdVCUwuVNiW:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L11)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

from a user's perspective, this type is called `validate.ValidateError`.
why not just call it `Error`. it would remove some stuttering: `validate.Error`.
</blockquote></details>

Done.

---

*[validate/error.go, line 21 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSr7V7RIXAi5-pNVrY:-KqU2CWrRmcu7sefqqQ-:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L21)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

`s/stack underflow/validate: stack underflow/`
</blockquote></details>

Done.

---

*[validate/error.go, line 52 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSrMpO5ypmAfiPlWNE:-KqU2DGygZcIHYVtVQsp:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L52)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

to match what is usually done in tests, I would rename `Expected` into `Wanted`.
and put `Got` before `Wanted`.
</blockquote></details>

Done.

---

*[validate/error.go, line 57 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSiKEzSYU3DuYJZF-B:-KqU2EKj29IGu0f407ls:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L57)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

no need to explicitly call `.String()`, let `fmt.Sprintf` use the `Stringer` interface. do this instead:
```go
return fmt.Sprintf("invalid type. got %s, want %s", e.Got, e.Expected)
```
</blockquote></details>

Done.

---

*[validate/operand.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSnYQ0QEpqvjlGYPkJ:-KqU2F2hALR56wr_hmss:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/operand.go#L1)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please add a license header.
</blockquote></details>

Done.

---

*[validate/validate.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSnarY63lRraZCrXe_:-KqU2FcsldxE3PSg0THL:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L1)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please add a license header.
</blockquote></details>

Done.

---

*[validate/validate.go, line 44 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSo6P1TYeSUftr5LRz:-KqU2GIeEB3l5Ak8lAR-:b-7ume3i) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L44)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

it's not clear to me why we do this.
is it a debugging leftover ?
</blockquote></details>

Yep, forgot to remove it.

---

*[validate/validate.go, line 47 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSs8VG_7sU1cPM3lW5:-KqU2aOnNn4ielGggZ3X:b-hyj23c) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L47)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

you should also probably return that error (and possibly "decorate" it) if that error is not `nil` (and not `io.EOF`.)
</blockquote></details>

Yep, although error decoration is already done inside the loop in VerifyModule.

---

*[validate/validate.go, line 301 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSq8o0oJAtfAno3k1i:-KqU6cqGFfD3yDzj5-Ao:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L301)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

could you note in the comment what are these remaining checks?
</blockquote></details>

Done.

---

*[validate/validate.go, line 323 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSq0UQJ7hQHZ8X0VJw:-KqU2kN2XBym329X9rR3:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L323)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

typo: `poppoed`
</blockquote></details>

Done.

---

*[validate/validate.go, line 338 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSomKCVbW87AjdPp9l:-KqU3zmRtwqzu6PNH94C:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/validate.go#L338)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please document this exported method.
</blockquote></details>

Done.

---

*[validate/vm.go, line 1 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSpj-XfoUIWKod3S3N:-KqU2nR-4m_4qUj2TL52:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L1)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

please add a license header.
</blockquote></details>

Done.

---

*[validate/vm.go, line 19 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSp7jicLb-jMZu_vfr:-KqU3-QqjOoTz6vPg3rt:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L19)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

I would just call it `code`.
</blockquote></details>

Done.

---

*[validate/vm.go, line 47 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqStlUyWbAODMXogdZ1:-KqU3vkA_PehjaHQPivj:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L47)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

that's fine for the moment (we don't really know the perf bottlenecks) but please put a TODO to use the direct, reflection-less `binary.LittleEndian.Uint32` method.
</blockquote></details>

Done.

---

*[validate/vm.go, line 52 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSu7qpwDlk5EKF6Hn5:-KqU3wb53MYTc_i0-2sL:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/vm.go#L52)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

that's fine for the moment (we don't really know the perf bottlenecks) but please put a TODO to use the direct, reflection-less `binary.LittleEndian.Uint64` method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by vibhavp** [comment]
Review status: 6 of 11 files reviewed at latest revision, 17 unresolved discussions.

---

*[validate/error.go, line 12 at r3](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqSqoPhCruy8YgJkeUr:-KqUAUBnTSu3OWxpreae:b-896fix) ([raw file](https://github.com/go-interpreter/wagon/blob/5dd541c0b11d5c4547c00b44707eaf0de291391f/validate/error.go#L12)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

> Offset   int
please document of what that `Offset` is (bytes, ...) and into what.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by sbinet** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[validate/validate.go, line 287 at r4](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqWk9POylAh_Kg4lB9M:-KqWk9POylAh_Kg4lB9N:b-dxmgpo) ([raw file](https://github.com/go-interpreter/wagon/blob/f619684681cac56ef2b1f7c8d0973bab28906469/validate/validate.go#L287)):*
> ```Go
> 			// Since this is possible only during program execution, we only
> 			// perform the static check for the function index mentioned
> 			// in the bytecode stream, that
> ```

the suspense is unbearable :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by sbinet** [comment]
Reviewed 1 of 5 files at r3, 3 of 4 files at r4.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by sbinet** [comment]
:lgtm: (now you just have to squash the validate-related commits together with a commit message `validate: new package` and some blurb explaining what it does)

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-:-KqYA70c2JemIhJ1CSwI:b5akyzy)*

**Comment by vibhavp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[validate/validate.go, line 287 at r4](https://reviewable.io:443/reviews/go-interpreter/wagon/13#-KqWk9POylAh_Kg4lB9M:-KqYEcVtaXg0xGCOf7fp:b-3eywoa) ([raw file](https://github.com/go-interpreter/wagon/blob/f619684681cac56ef2b1f7c8d0973bab28906469/validate/validate.go#L287)):*
<details><summary><i>Previously, sbinet (Sebastien Binet) wrote…</i></summary><blockquote>

the suspense is unbearable :)
</blockquote></details>

oops, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/go-interpreter/wagon/13)*

**Comment by sbinet** [comment]
thanks!

**Pull request merged**
